### ISSUE TITLE
User selling this script (Repo included)

### ISSUE THREAD

**Issue by badchulo** [ESX-PUBLIC/esx_corona#5]
https://github.com/FenerheroBTW/Esx_Cornavirus-Covid19-  (100% same script)

![imagen](https://user-images.githubusercontent.com/19668212/80917343-840b5980-8d5e-11ea-94a3-86c9eeea018e.png)

**Comment by jijamik** [comment]
Thx i'm gonna take a look :)

**Comment by jijamik** [comment]
Repo deleted and notified vendor thanx 👍

**Comment by badchulo** [comment]
NP (L)

Edit: I just read the channel. 
![imagen](https://user-images.githubusercontent.com/19668212/81459010-e8367f00-919d-11ea-9828-58af70ab86b1.png)

This guy still saying "Open a ticket bro" Amazing.

Thanks to you @jijamik
